default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test

production:
  primary: &primary_production
    <<: *default
    database: recipe_app_production
    username: recipe_app
    password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: recipe_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: recipe_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: recipe_app_production_cable
    migrations_paths: db/cable_migrate
